<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbc57tz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbc57tz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCbc57tz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCbc57tz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCbc57tz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cbc57tz',
    'container.build_id' => '4b2e51bd',
    'container.build_time' => 1678796510,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbc57tz');
